#!/usr/bin/env python3
# Copyright 2019 Katteli Inc.
# TestFlows.com Open-Source Software Testing Framework (http://testflows.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import os
import shutil
import argparse
import subprocess

parser = argparse.ArgumentParser(description="TestFlows - build script")
parser.add_argument("--debug", help="enable debugging", action="store_true", default=False)

current_dir = os.path.dirname(os.path.abspath(__file__))

def build_package(args, options):
    """Build package.

    :param args: arguments
    :param options: extra options
    """
    subprocess.run(["/usr/bin/env", "python3", "setup.py"]
                   + (["-q"] if not args.debug else [])
                   + ["sdist"]
                   + (options if options else []))

def build(args, options=None):
    """Build package.
    
    :param args: arguments
    :param options: build options, default: ``None``
    """
    if options is None:
        options = []
  
    if os.path.exists("dist"):
        shutil.rmtree("dist")
      
    build_package(args, options)

if __name__ == "__main__":
    args = parser.parse_args()
    build(args)
